name: Trigger action on CRON
on:
  schedule:
    - cron:  '*/30 * * * *'
jobs: 
  test-schedule:
    runs-on: ubuntu-latest
    steps:
      - name:  run every half an hour
        run:  echo "Running every 30 minutes"
